import { Wallet } from '@/types/wallet.types';
import { Offer } from '@/types/offer.types';
import { Transaction } from '@/types/transaction.types';
import { User } from '@/types/auth.types';

export const mockUser: User = {
    id: '1',
    full_phone_number: '+212612345678',
    phone_number: '612345678',
    country_code: '+212',
    phone_verified: true,
    phone_verified_at: new Date().toISOString(),
    first_name: 'Ahmed',
    last_name: 'Benali',
    email: 'ahmed@example.com',
    kyc_status: 'approved',
    kyc_verified_at: new Date().toISOString(),
    date_joined: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_active: true,
    // Alias
    is_verified: true,
    currency: 'MAD',
};

export const mockWallet: Wallet = {
    id: '1',
    userId: '1',
    currency: 'MAD',
    balance: 15000,
    availableBalance: 12500,
    pendingBalance: 2500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
};

export const mockOffers: Offer[] = [
    {
        id: '1',
        userId: '2',
        userName: 'Mamadou D.',
        sendAmount: 1000000,
        sendCurrency: 'GNF',
        receiveAmount: 950,
        receiveCurrency: 'MAD',
        exchangeRate: 0.00095,
        status: 'ACTIVE',
        expiresAt: new Date(Date.now() + 86400000).toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        userId: '3',
        userName: 'Fatima Z.',
        sendAmount: 2000,
        sendCurrency: 'MAD',
        receiveAmount: 2100000,
        receiveCurrency: 'GNF',
        exchangeRate: 1050,
        status: 'ACTIVE',
        expiresAt: new Date(Date.now() + 86400000).toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        userId: '4',
        userName: 'Youssef M.',
        sendAmount: 1500,
        sendCurrency: 'MAD',
        receiveAmount: 1575000,
        receiveCurrency: 'GNF',
        exchangeRate: 1050,
        status: 'ACTIVE',
        expiresAt: new Date(Date.now() + 86400000).toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const mockTransactions: Transaction[] = [
    {
        id: '1',
        userId: '1',
        type: 'EXCHANGE',
        status: 'COMPLETED',
        amount: 1000,
        currency: 'MAD',
        fee: 10,
        netAmount: 990,
        fromCurrency: 'MAD',
        toCurrency: 'GNF',
        exchangeRate: 1050,
        offerId: '1',
        reference: 'TRX-20241216-001',
        description: 'Échange MAD vers GNF',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        updatedAt: new Date(Date.now() - 3600000).toISOString(),
        completedAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '2',
        userId: '1',
        type: 'DEPOSIT',
        status: 'COMPLETED',
        amount: 5000,
        currency: 'MAD',
        fee: 0,
        netAmount: 5000,
        reference: 'TRX-20241215-002',
        description: 'Dépôt par carte bancaire',
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 86400000).toISOString(),
        completedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        id: '3',
        userId: '1',
        type: 'EXCHANGE',
        status: 'PENDING',
        amount: 2500,
        currency: 'MAD',
        fee: 25,
        netAmount: 2475,
        fromCurrency: 'MAD',
        toCurrency: 'GNF',
        exchangeRate: 1050,
        offerId: '2',
        reference: 'TRX-20241216-003',
        description: 'Échange MAD vers GNF',
        createdAt: new Date(Date.now() - 1800000).toISOString(),
        updatedAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
        id: '4',
        userId: '1',
        type: 'WITHDRAWAL',
        status: 'PROCESSING',
        amount: 3000,
        currency: 'MAD',
        fee: 30,
        netAmount: 2970,
        reference: 'TRX-20241214-004',
        description: 'Retrait vers compte bancaire',
        createdAt: new Date(Date.now() - 172800000).toISOString(),
        updatedAt: new Date(Date.now() - 172800000).toISOString(),
    },
];